apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-test
  namespace: argocd
spec:
  project: default
  sources: 
    - repoURL: 'https://charts.gitlab.io/'
      chart: gitlab
      targetRevision: 8.1.0
      helm:
        
        valueFiles:
          - $values/apps/gitlab-values.yaml
    - repoURL: 'https://github.com/margiesf/minikube-gitops.git'
      targetRevision: HEAD
      ref: values 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitlab-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
