apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-test
  namespace: argocd
spec:
  project: default
  source:
    chart: gitlab
    repoURL: https://charts.gitlab.io/
    targetRevision: 8.x.x # Έκδοση Chart
    helm:
    valueFiles:
        - gitlab-values.yaml
      parameters:
      - name: global.hosts.domain
        value: minikube.local
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
